version: "3.7"

services:
  mongo:
    image: mongo:latest
    ports:
      - '27017'
    volumes:
      - mongodata:/data/db
    networks:
      - app-network

  frontend:
    build:
      context: AppFront
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    networks:
      - app-network 

  backend:
    depends_on:
      - mongo
    build:
      context: AppBack
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/cluster0.65fr69g.mongodb.net
    networks:
      - app-network 

volumes:
  mongodata:

networks:
  app-network:
    driver: bridge