# //-------------------LOCAL------------------------//
# ####
# //MOSTRAR USUARIOS
# GET http://localhost:3000/api/users HTTP/1.1

# ####
# // MOSTRAR PRODUCTOS
# GET http://localhost:3000/api/producto HTTP/1.1
# autorizado:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQ1NzAwMDN9.SrBJxk5bzC4f4ZnIpoLK0LipaEFH-6MMc90_ahPLAAM
# ####
# // Register
# POST http://localhost:3000/api/users/register HTTP/1.1
# Content-Type: application/json

# {
#     "nombre":"julian",
#     "correo": "julian@gmail.com",
#     "contrasena":"contrasena"}

# ####
# // Login
# POST http://localhost:3000/api/users/login HTTP/1.1
# Content-Type: application/json

# {
#     "correo": "david@gmail.com",
#     "contrasena":"1234"
# }

# ####
# //Traer perrito
# GET http://localhost:3000/api/perros/perro HTTP/1.1
# Content-Type: application/json
# autorizado:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiNjUwZGM0NjcxYWFjZmQ0MTQxYzRlMjRmIiwidXN1YXJpb19yb2xlIjoibm9ybWFsIiwiaWF0IjoxNjk2MjEwNDk1fQ._GMaLBks0KcHQI8NUCFe3emn4UhH1yw7QXVABsK4TSw


# ####
# //crear perrito
# POST http://localhost:3000/api/perros/crearperros HTTP/1.1
# Content-Type: application/json
# autorizado:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiNjUwZGM0NjcxYWFjZmQ0MTQxYzRlMjRmIiwidXN1YXJpb19yb2xlIjoibm9ybWFsIiwiaWF0IjoxNjk2MjA5OTgyfQ.S2Po7afLDnZEIZUuzGuxzrXh1ZneurajJICGsVRVtr0

# {
#     "nombre":"prueba1",
#     "edad":1
# }


//----------------------Atlas------------------------//

####
//MOSTRAR USUARIOS
GET http://localhost:3000/api/users HTTP/1.1

####
// MOSTRAR PRODUCTOS
GET http://localhost:3000/api/productos HTTP/1.1
autorizado:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQ1NzAwMDN9.SrBJxk5bzC4f4ZnIpoLK0LipaEFH-6MMc90_ahPLAAM
####
// Crear producto
POST http://localhost:3000/api/productos HTTP/1.1
Content-Type: application/json

{
"nombre":"Menjarcito", 
"costo":"20",
"stock":"100",
"descripcion":"Alto contenido de Salmon"
}
####
// Register
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
    "nombre":"julian",
    "correo": "julian@gmail.com",
    "contrasena":"contrasena"}

####
// Login
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "correo": "david@gmail.com",
    "contrasena":"1234"
}

####
//Traer perrito
GET http://localhost:3000/api/perros/perro HTTP/1.1
Content-Type: application/json
autorizado:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiNjUwZGM0NjcxYWFjZmQ0MTQxYzRlMjRmIiwidXN1YXJpb19yb2xlIjoibm9ybWFsIiwiaWF0IjoxNjk2MjEwNDk1fQ._GMaLBks0KcHQI8NUCFe3emn4UhH1yw7QXVABsK4TSw


####
//crear perrito
POST http://localhost:3000/api/perros/crearperros HTTP/1.1
Content-Type: application/json
autorizado:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiNjUwZGM0NjcxYWFjZmQ0MTQxYzRlMjRmIiwidXN1YXJpb19yb2xlIjoibm9ybWFsIiwiaWF0IjoxNjk2MjA5OTgyfQ.S2Po7afLDnZEIZUuzGuxzrXh1ZneurajJICGsVRVtr0

{
    "nombre":"prueba1",
    "edad":1
}
